version: '2.3'

volumes:
  psql-data:
    driver: local

networks:
  customer-1-net:
    driver: bridge

services:
  database:
    image: postgres:10
    env_file:
      - .postgres.env
    networks:
      - customer-1-net
    volumes:
      - psql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  horizon:
    image: opennms/horizon-core-web:23.0.0-1
    init: true
    env_file:
      - .opennms.env
      - .postgres.env
    networks:
      - customer-1-net
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./horizon-etc:/opt/opennms/etc
      - ./horizon-data:/opennms-data
      - ../global-config:/opt/opennms-etc-overlay
    command: ["-s"]
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "http://localhost:8980/opennms/login.jsp"]
      interval: 1m
      timeout: 5s
      retries: 3
    ports:
      - "8001:8980"
      - "8101"
      - "61616"
      - "162/udp"
